language: csharp
mono:
  - latest

notifications:
  email: false

before_install:
  - "cd Test"

solution: ./Test.sln

install:
  - nuget restore ./Test.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release ./Test.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe -labels -nologo ./Test/bin/Release/Test.exe

after_script:
  - nunit-console Test/bin/Release/Test.exe
